### PR TITLE
Econ surveyweights

### PR DESCRIPTION
**Pull request by mle2718**
I need to get the trawl survey biomass to feed into the economic model.

I name changed  ``IJ1`` to ``EconIN`` because it was just too confusing for me.

The code runs, but I need help on two spots:

I borrowed lines 113-121 in ``runSim.R`` from the ``get_indexData`` function.  

Q1: is this coded up properly?
 obs_sumEconIN[y] <- get_error_idx(type=oe_sumIN_typ, 
                                            idx=sumEconIN[y] * **ob_sumIN**, 
                                            par=oe_sumIN)    
I don't quite follow what the ``get_error_idx`` function is doing and I don't know where ob_sumIN comes from.

Q2. what are the units of ``IN`` and ``waa``? Individuals and kilograms?

### CODE REVIEW

**Comment by mle2718** [comment]
@samtruesdell: Thanks
Do you know the answer to this:

Q2. what are the units of IN and waa? Individuals and kilograms?

**Comment by samtruesdell** [comment]
IN would be individuals numbers. waa is input as kg but converted to MT in the get_weightAtAge() function (https://github.com/lkerr/groundfish-MSE/blob/48e241220fa61b2a0df4b3ecdd364dbb7649189f/functions/popdy/get_weightAtAge.R#L79). Does that help?

**Comment by mle2718** [comment]
super helpful.  glad i asked, i figured would be kg.

**Comment by samtruesdell** [comment]
Sorry Min-Yang I missed some of your Qs here. ```get_error_idx``` is just a simple function to get index values that include observation error depending on the magnitude of the sd which is set in the species file. The way it's set up is that lognormal errors are the only option. In ```sumEconIN[y] * ob_sumIN```, ```ob_sumIN``` just represents observation error bias in the index -- it is also set as a prameter in the species files.

**Pull request merged**
